### ISSUE TITLE
The simulation results are inconsistent under the same parameters and conditions

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#105]
Dear Ubermag Team,
When I simulate a micromagnetic model with random initial magnetization state, I find that the simulated structure is slightly different without changing any parameters, as shown in the figure below
![image](https://user-images.githubusercontent.com/61874432/104461893-e35a8280-55ea-11eb-86a5-4fb0db6d9e4c.png)
![image](https://user-images.githubusercontent.com/61874432/104461905-e81f3680-55ea-11eb-93ba-317615c1be79.png)
![image](https://user-images.githubusercontent.com/61874432/104461932-ed7c8100-55ea-11eb-83f6-8b1d1e9399d9.png)
I don't know whether this result is due to the error of the simulation itself or other reasons. In order to make each random initial state consistent, I used ````random.seed```` But the simulation results are not completely consistent. Can you tell me why? Thank you for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. It is a bit difficult to understand what is an issue without looking at the code. Could you please show us the notebook?

**Comment by code-whale** [comment]
@marijanbeg ,OK, I'll attach my ipynb file, but I've simplified part of the code. In this file, we can still find that the number and location distribution of SK generated in the same case are slightly different. Thank you again for your patient help!
[different1_DMIandK.zip](https://github.com/ubermag/help/files/5809203/different1_DMIandK.zip)

**Comment by marijanbeg** [comment]
Thank you for the notebook. The issue is in this cell:

```
random.seed(2)
def init_random(point):
    m = 2 * np.random.random((1, 3)) - 1
    return m
```

You are setting the seed using Python's built-in `random`, but generating random numbers using `numpy`. The fix would be:

```
np.random.seed(2)
def init_random(point):
    m = 2 * np.random.random((1, 3)) - 1
    return m
```

By looking at your notebook, I can make a few other suggestions to make your coding easier:

1. Many constants are already in `micromagneticmodel.consts`. For example, instead of defining mu0 and gamma0 yourself, you can get them with `mm.consts.mu0` and `mm.consts.gamma0`.

2. To turn off the axes on your plots, you can just type `plt.axis('off')` instead of separately turning off labels, ticks, etc.

3. Typing `plt.show()` at the end of the plotting cell suppresses all text output.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you for your help! This solved my problem! Thank you for your valuable advice. Some of my code is too cumbersome. I will continue to learn to simplify them:)
