### ISSUE TITLE
Fields generated by reading .ovf files created using MuMax3 are all zero (apparently) 

### ISSUE THREAD

**Issue by askeyjw** [ubermag/help#112]
Hello again,

Apologies for what I think is the 4th question I've raised in the past few months. 

I've ran into a problem where I am trying to read in an .ovf file to define my magnetisation field, but when I access the array of a field slice all values are zero regardless of the position of the slice. It is particularly strange as I am still able to plot the magnetisation field across the whole system as I would expect using mpl(), which implies to me that somehow the actual values of mx, my, mz are somehow being masked (some limitation on significant figures in the data type perhaps) when input into an array. 

I have an example .ovf file which I have tried loading in as my magnetisation field but the file type is not supported to be loaded into this query box so I have included pngs of the slice plot and a screenshot of the output array. The details of the file are OVF 2.0 and data binary 4 type, the total length (x-coordinate) of the magnetic system is 6e-6m spanning from 0 to 6e-6m, and 100e-9m in the y- and z-coordinates. I thought that maybe the issue is in that the array is defaulting the values to zero due to some limitation either on the MuMax3 writing side, or in the reading of the file side of things, but not sure how this would be circumvented. 

A minimal example code is given below: 
`field = df.Field.fromfile('m000000.ovf') `
`field.plane(x=2.7e-6).mpl())` ### here we can plot the magnetisation field as expected ### 
`field.plane(x=2.7e-6).array` ### here we will see an array of zeros ### 
<img width="268" alt="OVF_Reading_Issue_Array" src="https://user-images.githubusercontent.com/67647269/107951463-4b0c4080-6f90-11eb-9ba4-eab8b1b4ef76.png">
![OVF_Reading_Issue_Plot](https://user-images.githubusercontent.com/67647269/107951468-4cd60400-6f90-11eb-85fd-dc9d4777e4cd.png)

As always, any help/advice/notes are greatly appreciated and thanks again for all the work on this. 

-Joe

**Comment by marijanbeg** [comment]
Hi @askeyjw, thank you for your question. When you ask for `field.array`, this returns a `numpy array`. This array is very long, so when you show it in Jupyter, it is shortened by default - you can see it is shortened where `...` are shown. In your case, only several cells from the "beginning" and several cells from the "end" are shown, which are zero because of Ms=0 (you have a disk geometry). The non-zero values in the middle are truncated. You can have a look here (https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array-without-truncation) on how to force printing full arrays.

Similarly, the value of field at a specific coordinate, you can ask using `field((70e-9, 70e-9, 0))`. This should return a non-zero value at that discretisation cell.

I hope this helps. If not, please let us know.
