### ISSUE TITLE
Subregion energy extraction

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#117]
Dear Ubermag Team,I am trying to calculate the energy of the sub-area, such as demagnetization energy, exchange energy and so on. I successfully sampled the sub-area according to your tutorial, but when I used ````data [xx] [subregion]````(I think the code to get the energy of the subregion should be ````data [xx] [subregion] .table.data````, maybe I misunderstood it）, the system reported an error as shown in the figure below. Can you tell me why this is the reason? is it that ubermag does not support this function at present or my method is wrong? thank you again for your patient help!
![image](https://user-images.githubusercontent.com/61874432/110791003-adfda880-82ac-11eb-8083-0667cea9f827.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. `data` is a `Data` object. When you index it once ('data[16]'), you get an individual drive. Drive cannot be sampled using a subregion. You have to index it again, to get a specific step - like you did in previous cells (`data[16][0]`).

Table object (`system.table`) contains scalar data only for the entire system and it cannot be sampled for an individual region. Computing the energy of a subregion is a non-trivial problem because energy of a subregion does not depend only on its magnetisation, but also on the energy of its surrounding. What I can suggest is the following:

1. Compute the energy density of the entire sample - `w = oc.compute(system.energy.density, system)`. This gives you the energy density scalar field of the entire sample.
2. `w` is a scalar field and can be sampled - `w[subregion]`
3. By integrating `w` over the volume, you should get the energy of a subregion: `df.integral(w[subregion]*df.dV)`.

Please let me know if this works. This is an interesting question and it would be cool if you can make a tutorial for other about this.

I am going to keep this question open until we get a confirmation if it is resolved.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you very much for your help. This is definitely an effective method. I used your code to calculate the exchange energy of the sub-area as shown in the following figure (I think this is correct), but I still have a problem, that is, for example, the energy of the whole system I can extract different file data through ````data []````, and when I use ````oc.compute````, it will also generate a file called compute-0,1. However, these files are not shown in the ````data.info```` table, which makes it impossible for me to quickly extract different files. Is there any way to solve this problem? Thank you again for your help!
![image](https://user-images.githubusercontent.com/61874432/110795188-89f09600-82b1-11eb-85b7-18bed5bdd436.png)
![image](https://user-images.githubusercontent.com/61874432/110795292-a391dd80-82b1-11eb-898c-26bdc3f62160.png)
![image](https://user-images.githubusercontent.com/61874432/110795337-ac82af00-82b1-11eb-9a29-af6a99f19f05.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your confirmation. Unfortunately, this is not possible because `compute` directories are not real drives that can be analysed in the same way - their metadata differ substantially.

If I understand right, you are trying to compute the exchange energy for different steps in a single drive. Am I right?

You can try to do that with:
```
tmp_system = system
tmp_system.m = data[drive][step]  # use drive and step you want
w = oc.compute(tmp_system.energy.exchange.density, tmp_system)
Eex = df.integral(w*df.dV)
```

The idea here is to create a temporary system object we can call compute method on. Could you please try if this works?

**Comment by code-whale** [comment]
@marijanbeg ,Thanks for your help! Your code is very effective and has achieved the function I want. I am using an energy minimization driver, and there is no problem with your code under this driver. I successfully extracted the exchange energy item in data [16]! I think my problem has been solved! You can turn off this problem at any time! Thank you again for your help!
![image](https://user-images.githubusercontent.com/61874432/110798337-05077b80-82b5-11eb-9086-c509433d3735.png)

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. I am closing this issue now.
