### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#129]
Hello ubermag team,
 
I've tried to install ubermag additionally in one of my desktop. 
Conda installation failed as 
Solving environment: failed with initial frozen solve. Retrying with flexible solve
Solving environment: failed with current_repodata.json, will retry with next repodata source. 

This happens both in Windows and Linux operating system. 

I installed ubermag in sperate environment and also set channel priority as flexible, but still same problem exists.

Then follwed advanced installation steps to install using pip. But when I tried to open jupyter notebook I got an winerror 127. 

I'm trying to install ubermag for past few days. Any comments will be really helpful. Thank you,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, I am sorry you experienced this error. Could you please try the following two things:

1. Make sure you install Ubermag in a fresh Python 3.8 environment (`conda create --name ubermag python=3.8` and then `conda activate ubermag`).
2. Explicitly specify the Ubermag version (`conda install --channel conda-forge ubermag=0.51`)

Please let us know if the problem is still there.

**Comment by Ponsudana** [comment]
Hello @marijanbeg Thanks for your help.

I mentioned the ubermag version as 0.51 and got
Collecting package metadata (current_repodata.json) : done
Solving environment: failed with initial frozen solve. Retrying with flexible solve
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (current_repodata.json) : done
Solving environment: done and installed.

I'm Sorry, maybe I should have waited a bit longer for the environment to solve for the third time. 
Thanks for your constant support.

**Comment by marijanbeg** [comment]
Great, thank you for letting us know.
