### ISSUE TITLE
Mumax backend on Ubermag

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/help#131]
Hey,

I'm trying to use Mumax3 as my calculator with Ubermag. I have tried using `mumaxc` as per this [repo](https://github.com/ubermag/mumax3c). All of the information on the tutorials relates to the OOMMF and Docker runners, so I don't know where to look. Has the Mumax package changed? Also, while I am on the topic, there is a useful feature on mumax to load a 2D geometry from an image, is there something similar for Ubermag?

Thanks

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, thank you for your question. mumax3c is still under development. Unfortunately, we do not have enough resources to dedicate to this effort, which is why the development is slow. Please keep an eye on issue #62, where we will update everybody about the progress. Thank you for your patience and understanding.
