### ISSUE TITLE
Calculate the velocity of skyrmions or skyrmionium

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#132]
Dear Ubermag Team, I would like to ask how to calculate the speed of skyrmions or skyrmionium. Through the method you taught me before, the center coordinates of skyrmions can be calculated, but for skyrmionium, its topological charge is 0, so I can't calculate its center coordinates, and it's too cumbersome to calculate the speed by calculating the distance between the center coordinates and dividing it by the time step. I would like to ask if you have a simple way to calculate the speed of skyrmions and skyrmionium. Thank you very much for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, unfortunately, there is no simple way of computing the velocity of skyrmionium since its topological charge is zero. The formulas I sent you earlier work for a skyrmion since you can plot the coordinate vs. time relationship and extract velocity from the slope. I guess the main question here would be how to compute the skyrmionium centre from the magnetisation field. If you find a good way of doing that, we would be interested in seeing your solution.

**Comment by zkhodzhaev** [comment]
"The formulas I sent you earlier work for a skyrmion since you can plot the coordinate vs. time relationship and extract velocity from the slope. " - can I get them too?

**Comment by marijanbeg** [comment]
For completeness, most details related to this issue are discussed in https://github.com/ubermag/help/issues/122
