### ISSUE TITLE
Installation in WSL

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/help#134]
Hi,

I'm trying to install in Windows Subsystem for Linux. I have an issue in the step `make build-with-all` as described in the Advanced Installation section for Linux. I get the following error:

`<7584> pimake 2.0a1  error:
couldn't execute "/tmp/build/80754af9/tk_1592503156360/_build_env/bin/x86_64-conda_cos6-linux-gnu-ranlib": no such file or directory
1 Error(s) detected
----------- 2021-May-28 12:45:09
Stack:
couldn't execute "/tmp/build/80754af9/tk_1592503156360/_build_env/bin/x86_64-conda_cos6-linux-gnu-ranlib": no such file or directory
    while executing
"Platform IndexLibrary vf"
    (while building target '/home/akravasthewise/oommf/oommf/pkg/vf/linux-x86_64/libvf.a')
    (while building target '/home/akravasthewise/oommf/oommf/app/mmdisp/linux-x86_64/condispsh')
    (while building target '/home/akravasthewise/oommf/oommf/app/mmdisp/linux-x86_64/appindex.tcl')
    (while building target '/home/akravasthewise/oommf/oommf/app/mmdisp/all')
    (procedure "Recursive" line 5)
    invoked from within
"Recursive all"
    (while building target '/home/akravasthewise/oommf/oommf/app/all')
    (procedure "Recursive" line 5)
    invoked from within
"Recursive all"
    (while building target '/home/akravasthewise/oommf/oommf/all')
    ('MakeRule' proc 'Build' line 51)
(message truncated)
<7581> oommf.tcl 2.0a1  panic:
child process exited abnormally
make: *** [Makefile:10: build] Error 1`

Not sure how to proceed.

Thanks

**Comment by fangohr** [comment]
I don't know either - I haven't got access to a windows machine with the WSL. 

You can get the original OOMMF sources from https://math.nist.gov/oommf/software-20.html

You could download the sources and try to compile them directly. (You will probably run into the same error, as the git repository offers exactly the same sources [in the `oommf` subdirectory of the git repository], but it is worth double checking this is the case.)

You could also check the mumag mailing list (https://www.ctcms.nist.gov/~rdm/mumag.org.html) to see if the issue has been raised before, or raise it yourself.

Finally, another question: could you work with the windows executable that can be downloaded from https://math.nist.gov/oommf/software-20.html, and use this with Ubermag within Windows (rather than WSL)?
