### ISSUE TITLE
Time-dependent current in the Slonczewski term

### ISSUE THREAD

**Issue by DebanjanPolley** [ubermag/help#135]
Hi,
When using the Slonczewski term to simulate the dynamics of a magnetic dot, is it possible to introduce a  time-dependent current term (J(t), instead of J)? If possible, is there any example on how to do that?

**Comment by marijanbeg** [comment]
Hi @DebanjanPolley, thank you for your question. Ubermag does not support time-varying currents in the Slonczewski term. However, we can look at this (@lang-m) and attempt to include it in the next release. What current time dependence do you need?

**Comment by DebanjanPolley** [comment]
That would be great @marijanbeg ! I am thinking about a sending a current pulse with a high value (J = Jc), for a fixed time duration ( picosecond to nanosecond range). It would be nice if the user can define this time duration and the current amplitude. Also, it would be fantastic if we can use to use an experimentally measured current profile (J as a function of time) as the input in the Slonczewski term and the code can extrapolate/interpolate to fit in the dynamics term.

**Comment by marijanbeg** [comment]
Hi @DebanjanPolley, thank you for the clarification. Current pulses are already available. You can simply apply current, simulate using `TimeDriver` for some time `T`, then remove Slonczewski term from the dynamics equation (`system.dynamics -= mm.Slonczewski(...)`), and drive the system using `TimeDriver` again.

Unfortunately, using an arbitrary time-dependence would not be possible due to the OOMMF limitations.

**Comment by DebanjanPolley** [comment]
Actually, I was trying to simulate the effect of spin-orbit torque on a ferromagnetic dot (on top of a non-magnetic metal). In this case, experimentally, I am passing a short (ps to ns range) current pulse through the non-magnetic metal and observing the dynamics of the ferromagnet due to the spin current generated due to SOT. I was thinking that I could use Slonczewski term (as it would take care of the effect of field-like and damping-like torque) with the short current pulse as the current term there. I have seen papers for similar type of simulations with OOMMF. Is it possible to do it using Ubermag?

**Comment by marijanbeg** [comment]
Hi @DebanjanPolley, thank you for the clarification. Yes, applying a current pulse is possible without any extensions. Here is the draft of an idea:

```python
system.dynamics = ... + mm.Slonczewski(...)  # apply current
td = oc.TimeDriver()
td.drive(system, t=pulse_duration)
system.dynamics -= mm.Slonczewski(...)  # turn off the current
td.drive(system, t=...)  # drive system without current
```

We intend to have a sine-wave current pulse in the next release of Ubermag.

**Comment by DebanjanPolley** [comment]
Thanks @marijanbeg . I will try this method.

**Comment by DebanjanPolley** [comment]
Hi @marijanbeg , I tried your method.
The first time driver with the Slonczewski term in the dynamics is running and showing expected behavior. But then I removed the Slonczewski dynamics term and then the time driver is showing this error (attached). Can you help me out?


<img width="1142" alt="Screen Shot 2021-06-13 at 6 15 31 PM" src="https://user-images.githubusercontent.com/62617740/121828114-76b7e280-cc73-11eb-8b9c-3cfb91b91cfa.png">

**Comment by marijanbeg** [comment]
Hi @DebanjanPolley, thank you for the update. This is unexpected. Could you please send us the notebook (after removing all confidential information) so that we can have a more detailed look?

In the meantime, could you please try turning off the current using
```
system.dynamics.slonczewski.J = 0
```
instead of the `system.dynamics -= mm.Slonczewski(...)` line.

**Comment by DebanjanPolley** [comment]
Hi @marijanbeg , 

I have rechecked my notebook. Now, all these three commands give me the same result.

```
system.dynamics -= mm.Slonczewski(J = Jc, mp = (0, 1, 0), P = P, Lambda = L, eps_prime = ep)
system.dynamics.slonczewski.J = 0 
system.dynamics = mm.Precession(gamma0=gamma0) + mm.Damping(alpha=alpha) + mm.Slonczewski(J = 0, mp = (0, 1, 0), P = P, Lambda = L, eps_prime = ep)
```


Previously, I was getting error. I found out that I need to define a new time driver (as shown)

```
td = oc.TimeDriver()
td.drive(system, t=T, n=N)
```

after I removed the Slonczewski term from the dynamics. For reference, I have attached here the corresponding notebook.


[Simulation-Copy.zip](https://github.com/ubermag/help/files/6679124/Simulation-Copy.zip)

**Comment by marijanbeg** [comment]
Hi @DebanjanPolley, thank you for letting us know. This is a bug - thank you for catching it.

**Comment by marijanbeg** [comment]
A summary of the bug:

- First time we call `drive` method, if evolver is not explicitly defined by the user, we choose one automatically (`driver.evolver`).
- The next time we call drive method, driver thinks evolver is set by the user since `driver.evolver` was previously set. Therefore, it does not search for the best possible driver again.
