### ISSUE TITLE
mmarchive killed

### ISSUE THREAD

**Issue by Siyuanq** [ubermag/help#174]
Hello:
    It always reports "mmarchive killed" when I run simulations. The simulation can be run, but the system.table.data only inculdes one row, without time-varying data.

**Comment by lang-m** [comment]
Hi @Siyuanq,
I transferred your issue to our help repository, the repository we ask you to use when having [questions](https://ubermag.github.io/help.html).

Reporting ``mmarchive killed`` is correct and expected. Based on your description my guess is that you are using ``MinDriver`` instead of ``TimeDriver``, please have a look at https://ubermag.github.io/workshop/tutorials/energy-equation.html and https://ubermag.github.io/workshop/tutorials/dynamics-equation.html.

Without knowing your actual code we cannot really help you. If you need more help, please upload your notebook.

**Comment by lang-m** [comment]
@Siyuanq Has your original question been answered?

**Comment by lang-m** [comment]
The new version of ubermag (`0.61.0`), released today, fixes the problem of `mmarchive killed` showing up.
