### ISSUE TITLE
No attribute k3d_vector for the field 

### ISSUE THREAD

**Issue by okmike** [ubermag/help#179]
Hi, I download the Workshop Session 2, 2 Energy Equation to run locally on Jupyter, already updated Ubermag to 0.60.0 and use Chrome for Jupyter. There is a issue for cell 3, after defining the field as system.m and the issue is "AttributeError: Object has no attribute k3d_vector." Thank you for your help!
![123](https://user-images.githubusercontent.com/37909931/135986843-729105c8-e45c-4113-8796-cbc7c7f5ec36.png)
p!

**Comment by okmike** [comment]
![1223](https://user-images.githubusercontent.com/37909931/135987290-9287c227-a8fc-49a0-a103-f33db1c4024f.png)
But the online Binder version just works fine

**Comment by marijanbeg** [comment]
Hi @okmike, thank you for your question. In Ubermag 0.6, we changed the user interface for plotting. Instead of `field.k3d_vector()`, it is `field.k3d.vector()`. You can find more information in the documentation: https://ubermag.github.io/documentation/ipynb/discretisedfield/field-k3d-visualisation.html. This will allow us to extend the plotting functionality in the future.

Regarding Binder, we still have not updated the Ubermag on Binder, which is why the old interface still works. We will do that soon. :)

I will keep this issue open until we update Binder.

**Comment by marijanbeg** [comment]
Hi @okmike, I investigated this issue in more detail. Binder for `discreditedfield` is updated. You encountered this issue in the `workshop` repository. We will deal with this update soon.
