### ISSUE TITLE
Regarding Slonczewski Torque-Urgent

### ISSUE THREAD

**Issue by vinodnaikb** [ubermag/help#222]
[Doubts on Slonczewski Torque.pdf](https://github.com/ubermag/help/files/9425566/Doubts.on.Slonczewski.Torque.pdf)
I have a few doubts regarding the Slonczewski term. I request you please address the issues. @swapneelap @samjrholt

**Comment by swapneelap** [comment]
Hello @vinodnaikb,
Apologies for the late reply.

1. The LaTex representation of the Slonczewski term will be fixed by this ubermag/micromagneticmodel/pull/58 pull request. Let me add that `ubermag` does not use any micromagnetic calculators of its own, but delegates the work to OOMMF internally. Hence, even though there was a mistake in representation of Slonczewski term in `ubermag`, your simulation results calculated through `oommc` should be correct.
2. The value of $t$ in $\beta$ is calculated internally by OOMMF. Please refer to [this](https://kelvinxyfong.wordpress.com/research/research-interests/oommf-extensions/xf_stt/).

**Comment by swapneelap** [comment]
I have merged the PR and it should fix the LaTex representation in the following `micromagneticmodel` version.
