### ISSUE TITLE
OOMMF Docker Image RuntimeError

### ISSUE THREAD

**Issue by CRTejaswi** [ubermag/help#231]
While running the [choosing-runner](https://github.com/ubermag/workshop/blob/2020-06-18_2020-07-02/tutorials/choosing-runner.ipynb) notebook on Windows, I'm getting the following error:

![error](https://user-images.githubusercontent.com/24400066/200673281-2863ba2e-68a5-4072-9ae1-b2eb95593cc1.png)

The error log from Docker Desktop is:

```
Logging to file "/usr/local/oommf/oommf/boxsi.errors"

[Boxsi<9-1f065584e14e-oommfuser> 20:55:51.029 2022-11-08] 2.0a1 infolog:
Start: "/io/skyrmion.mif"
Options: -exitondone 1 -threads 4

[Boxsi<9-1f065584e14e-oommfuser> 20:55:51.052 2022-11-08] 2.0a1 LoadProblem error:
Error loading /io/skyrmion.mif:
        Unrecognized Specify Block: 
  Oxs_DMI_Cnv_z:dmi
<1> oommf.tcl 2.0a1  panic:
child process exited abnormally
Boxsi run end.
```

How may I resolve this issue?

**Comment by fangohr** [comment]
It looks like your ommf version might be too old. Can you run this command in an shell:

`docker images` ?

We only need the lines that mention `oommf` in the left column. I expect something like

```
oommf/oommf                       20a3                ce109884a240   13 months ago   849MB
ubermag/oommf                     latest              66275125684d   2 years ago     682MB
```

**Comment by CRTejaswi** [comment]
```
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
ubermag/oommf   latest    66275125684d   2 years ago   682MB
```

**Comment by CRTejaswi** [comment]
Thank you! Replacing 'ubermag/oommf' with 'oommf/oommf' resolved it.

**Comment by fangohr** [comment]
Well done, you have fixed the problem, while I was writing the following reply. 

I'll post it anyway in case it helps someone else later.

As you have discovered, in the notebook at , there is the line
```
docker_runner = mc.oommf.DockerOOMMFRunner(image='ubermag/oommf')
```
This refers to the `oommf` image on dockerhub in the Ubermag organisation. We have since moved [the `oommf` image into the `oommf` organisation](https://hub.docker.com/r/oommf/oommf) (which is a little tidier as the same image could be used to execute oommf without Ubermag).

Please change the above line to 
```
docker_runner = mc.oommf.DockerOOMMFRunner(image='oommf/oommf')
```
to use the more up-to-date oommf docker image.

**Comment by Potential11** [comment]
I've been looking for a long while about how to use docker running oommf ,I meet  the issue that energy with dmi cannot work on windows .And a short tutorial published before cannot be found(404).Now I just add a line`docker_runner = mc.oommf.DockerOOMMFRunner(image='oommf/oommf')`can solve my issue. Thanks
