### ISSUE TITLE
The image saving problem in the version of 0.66 Ubermag

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#233]
Hi!
     When I use matplotlib to draw a colorbar, the saved images in eps format are displayed incorrectly, while other formats are displayed correctly, such as png, tif. 
      It is running by ubermag in the version of 0.66, and other versions are normal.
![colorbar in eps](https://user-images.githubusercontent.com/81371568/211232901-51147a72-bad1-483c-85da-ebacc8dde797.png)
![colorbar in tif](https://user-images.githubusercontent.com/81371568/211232904-ef0b7d1e-ac1b-4208-8c53-97e8f3af0db7.png)

**Comment by code-whale** [comment]
With regard to the question raised by @ZhiyuZhang001 , the following is the code to reproduce the problem:
````
import matplotlib as mpl
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(8,0.8))
norm = mpl.colors.Normalize(vmin=0.8, vmax=0.88)
cmap = mpl.cm.viridis
cbar = mpl.colorbar.ColorbarBase(ax, cmap=cmap,norm=norm,
                                ticks=[0.8,0.84,0.88],orientation='horizontal')
cbar.set_label(label=r'$K_{v}\ (MJ/m^{3})$',fontsize=40)
cbar.ax.tick_params(labelsize=35)
plt.savefig('cbar1.eps',dpi=600,bbox_inches='tight')
plt.show()
````
The code can run normally in the ubermag=0.64 environment and save eps files normally.

In addition, in the latest version of ubermag, the progress bar pointed to by ````verbose=2```` cannot be displayed normally. Is this caused by the incompatibility of the updated ipywidget? We look forward to your reply.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/61874432/211234216-7fe79d48-d8cb-45d0-b5f5-8a61fd34cad6.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/61874432/211234288-f034ec1f-2b3d-42f8-97a8-c195ef1f7f7c.png">

**Comment by code-whale** [comment]
I searched the matplotlib packages of the two versions and found that the matplotlib versions in the two environments are different. 
In ubermag=064：
````
matplotlib-base           3.5.2            py38h1b6b9d1_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
````

In ubermag=066：
````
matplotlib-base           3.6.2            py38hcb346ec_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
````

In addition, my colleagues @ZhiyuZhang001  installed ````matplotlib=3.6.2, python=3.9```` in the base environment and tested it. We found that the eps file could not be saved correctly. We guessed whether the problem originated from matplotlib. We look forward to your reply.

**Comment by fangohr** [comment]
That sounds like a `matplotlib` issue, sorry. Have you checked the issue tracker there?

Perhaps you can save a pdf and convert it to eps?
