### ISSUE TITLE
Unable to use spatial variation DMI in fixed subregions.

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#238]
Dear Ubermag Team,

I am writing to seek assistance with a simulation of a spin valve that I have been working on. Specifically, I am attempting to create a structure that resembles a spin valve, where the direction of magnetic moment in the bottom ferromagnetic layer is fixed by exchange bias.

To achieve this, I have been attempting to use the fix_subregions function. However, when I attempted to incorporate the parameter D for spatial variation, I encountered an error in the program.

I have attached my simulation file for your review, and I would greatly appreciate any help or guidance you could offer to help me resolve this issue. Thank you for your ongoing support, and I look forward to hearing from you soon.

Best regards,
Jinyu Zhang
[fix.ipynb.zip](https://github.com/ubermag/help/files/10950174/fix.ipynb.zip)

**Comment by lang-m** [comment]
Hi @code-whale, the problem is that the names of your subregions do not match the names used for `D`:
Your subregions are
```python
subregions = {'fix':df.Region(p1=(-d/2,-d/2,-3e-9),p2=(d/2,d/2,-1e-9)),
              'NM':df.Region(p1=(-d/2,-d/2,-1e-9),p2=(d/2,d/2,1e-9)),
              'free':df.Region(p1=(-d/2,-d/2,1e-9),p2=(d/2,d/2,3e-9))}
```
but you try to create D using unknown `region1`, `region2`, and `region3`:
```Python
D={'region1':2e-3,'region2':0,'region3':1e-3}
```

When defining D you must use the names of the `subregions` you have defined, i.e. in your example `fix`, `NM` and `free`. In case you need variations "within" a subregion you have to subdivide it into multiple smaller subregions.

**Comment by code-whale** [comment]
@lang-m I apologize for my negligence and thank you for your help!
