### ISSUE TITLE
Strange behaviour of hysteresis curve for an time-varying field

### ISSUE THREAD

**Issue by gabriolacomunista** [ubermag/help#296]
I've been trying to simulate hysteresis for magnetite nanocubes, but the loops show a rather strange behaviour. I am basically trying to replicate part of the results from a paper by N.A. Usov: [https://www.nature.com/articles/s41598-017-18162-8#Sec2](url). The author apparently didn't use Ubermag nor OOMMF to do the simulations, but my results differ drastically from his. Here's an example:

My curve            | Usov's curve (the one in black)
:-------------------------:|:-------------------------:
![image](https://github.com/user-attachments/assets/11a1cef6-22d6-4cbc-9182-b0a3a6aae7b2)  | ![image](https://github.com/user-attachments/assets/0c18feda-889c-4df6-9f44-fd98f8a4bf9b)

Even though my particle size for the example above is slightly different(60nm) from the original paper, I don't think this should create such a difference. All of the parameters I used are the same as the original paper.  The cell size was chosen in order to abide by the limitations imposed by exchange length and other characteristics of the material.

The .ipynb file of the simulation is attached. What should I do? Could you provide insight into what's going wrong with my simulation?!

Thanks for your help!
[AC hysteresis Fe3o4 nanocubes.zip](https://github.com/user-attachments/files/16664902/AC.hysteresis.Fe3o4.nanocubes.zip)

**Comment by fangohr** [comment]
Dear @gabriolacomunista, 

It is quite a challenge to exactly reproduce a published results. There are many reasons why this may be hard, including mistakes made by you or the original author, incomplete documentation of the procedure to be followed, lack of the simulation tool that was used, etc.

If you change any of the parameters (size, materials, etc) and/or the simulation method (other discretisation, or even only different software), you are likely to get deviations which could either indicate different physics due to the changed parameters, or differences that originate in the changed numerical method, or bugs in either of the software implementations. 

Your question seems to be: "I have run a simulation that is not quite the same as a published simulation, and I get different results." What I tried to outline above is: It is expected that you get different results.

Your first step should be to reproduce the publication results. This will ensure you understand the problem. It also means you check that the published results are correct. (If they are not, or at least not correctly described, it will be very hard to base your own research on this.) Once you have succeeded with this, you can start to vary parameters and do something new.

You need to contact the author for details on the simulation to fully reproduce the results. As the paper is published in a Nature journal, the authors are [expected to help you reproduce their findings](https://www.nature.com/nature-portfolio/editorial-policies/reporting-standards).

Is any case, this is not a Ubermag question.
