### ISSUE TITLE
Zhangli dynamics, Test Attribute Error

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#44]
Hi,

I have upgraded oommfc using conda as,
"conda upgrade oommfc"
After running the test, I got an Attribute Error.
![AttributeError](https://user-images.githubusercontent.com/43433451/63762628-ca134200-c8e0-11e9-8207-8af56c8f7557.png)
Kindly help me to rectify this error.

I can't import oommfc in jupyter notebook too, it shows same attribute error.

Thanks,
Ponusdana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, thank you for reporting the issue. Could you try installing `oommfc` in Python 3.6 environment and let us know the outcome.
```
conda create -n environment_name python=3.6
conda activate environment_name
conda install --channel conda-forge oommfc
```

`environment_name` can be any name you choose.

**Comment by Ponsudana** [comment]
It worked. oommfc was successfully imported.

But got an error in field object as,

"Field object has no attribute plot_plane"
![Field object error](https://user-images.githubusercontent.com/43433451/63767984-aa821680-c8ec-11e9-9daa-13fdad6fda4e.png)

**Comment by marijanbeg** [comment]
Great. Please refer to new documentation for `discretisedfield` (https://discretisedfield.readthedocs.io/en/latest/), especially tutorials 9 and 10. The new interface is `system.m.z.plane('z').mpl()`

I will close this issue now, but feel free to reopen it.

**Comment by Ponsudana** [comment]
Thank you @marijanbeg

**Comment by marijanbeg** [comment]
You are more than welcome @Ponsudana! Please refer to the new documentation for different packages which are now a part of Ubermag: https://ubermag.readthedocs.io/en/latest/ipynb/04-tutorial-micromagnetic-tutorials.html. We added a lot of new functionalities and the interface changed a bit because of that. One small warning: for 3D visualisations using k3d, it is best to use Chrome as a browser.

Please let us know if you notice any problems or need any help from our side.

**Comment by Ponsudana** [comment]
Thank you so much for the tutorials. I'll check new documentation for my future works.

Thanks for the constant support @marijanbeg
