### ISSUE TITLE
Pulse field

### ISSUE THREAD

**Issue by janegmonge** [ubermag/help#48]
Hello I am new using JOOMMF and I was wondering if it is possible to consider a magnetic field that depends on the time and stage, like the pulse.mif or acsample.mif examples in OMMF?
I will appreciate any help. 
Thank you...

**Comment by marijanbeg** [comment]
Hi @janegmonge, thank you for your question. Changing the external field value at every stage of simulation by OOMMF can be very confusing for the user, because this functionality can be obtained as a part of Python interface. For example, in the case of the time driver:

```
for time in time_array:
    system.hamiltonian.zeeman.H = field_value
    td.drive(time)
```
Please feel free to reopen this issue if I did not answer your question.
