### ISSUE TITLE
Change the direction of Current in ZhangLi Dynamics

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#57]
Hello,

For ZhangLi STT Dynamics, we define it by,

**system.dynamics+=oc.ZhangLi(u=u, beta=beta)**
where _u is the velocity along the x-direction_

Previously we define the direction of current by,
**system.dynamics += oc.STT(u=(ux, 0, 0), beta=beta)**

After the update, it predefined along the direction of x and "u" allow only type(value) = numbers.Real.

Is there any possible way to change the direction of the current?

Thank you,
Regards,
Ponsudana.

**Comment by marijanbeg** [comment]
Hi @Ponsudana, the OOMMF extension, on which ZhangLi is based on, can simulate only spin-polarised currents in the x-direction. We had (ux, 0, 0) as an input vector before, which was a bit misleading because it leaves an impression that any vector is allowed. Therefore, we changed it to scalar input, asking explicitly only for the velocity in the x-direction. In summary, in this case, we are limited by the OOMMF extension capabilities.

**Comment by Ponsudana** [comment]
Hi @marijanbeg, Thanks for the clarification. 
I'm happy with the results using ZhangLi dynamics.
For my future works to change the current direction will Special Dynamics be helpful?
