### ISSUE TITLE
plot regions for MPL

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#59]
There is a command `mesh.k3d_regions()` (for example in https://oommfc.readthedocs.io/en/latest/ipynb/04-tutorial-dmi.html, input cell [10] at the moment).

Is there an equivalent command or example code how to visualise the regions with MPL? If not, could this be added? (Couldn't find it in https://discretisedfield.readthedocs.io/en/latest/ipynb/09-tutorial-matplotlib-visualisation.html).

**Comment by marijanbeg** [comment]
I agree this would be a useful option, but there are several problems I noticed when I implemented this:

- If we plot the regions using lines only, the plot is very messy and difficult to interpret, especially if there are more than 2 regions. Matplotlib usually scales the plot in the weird way, which makes it even more difficult.
- If we decide to color regions, we must make sure that when plotted the sample is rotated the right way so the regions can be seen, because the rotation by the user is not allowed.

Therefore, I assumed this function would more frustrate users than be of use to them, since it is only used for inspection and decided to remove it.

**Comment by fangohr** [comment]
Fair point. 

I imagine that in most of the cases this plot is required the quickly debug the region definitions, often for very simply geometries and regions: for example 2 or 3 regions in layers.
This is the use case I would like to support well and make easy to debug, and am happy to accept that this would not serve all use cases.

I would suggest to colour regions, and to allow in the visualisation command to plot the domain from 6 different views: +x, -x, +y, -y, +z, -z. The view could be a command line argument.

We could go even further (probably a bad idea?) and by default plot 6 different views from all directions (if no argument is given).

For more complicated regions (in particular where one is embedded inside another one), this will not be sufficient, but I think such users will be more advanced and need less support in figuring out their region definitions.

**Comment by marijanbeg** [comment]
Ok, I will try to implement something like that as soon as possible.

**Comment by marijanbeg** [comment]
This is now implemented on master in `discretisedfield`. A new pip and conda package will be released soon.
