### ISSUE TITLE
Standard problem 3 with different answers

### ISSUE THREAD

**Issue by okmike** [ubermag/help#64]
Hi, I have a problem with one variable in standard problem 3 , the discretisation in one dimension N which is defined in the function minimise_system_energy. The tutorial defines the N = 16 and if I change N to 20 or 25, the final result will be very different from the one in the tutorial. I am new to the ubermag but should not the larger N (smaller cellsize for mesh) leads to more accurate results? Thank you for replying.
![a](https://user-images.githubusercontent.com/37909931/77223945-10d9c980-6b9c-11ea-8f41-e0dc71acc30a.png)

**Comment by marijanbeg** [comment]
Hi @okmike,

Thank you very much for your question. Please note that standard problem 3 is defined so that the length of the sample is expressed in exchange lengths, so talking about the discretisation as usual is not that straightforward (A depends of lex as well). If you rewrite the functions so that lengths are not in units of exchange length, then it should not depend on the discretisation directly.

Please let me know if you have any further questions.

**Comment by okmike** [comment]
Thanks for your replying. I checked the reference website for the Standard Problem 3 at https://www.ctcms.nist.gov/~rdm/mumag.org.html. In the description of the problem, it said that the "The results should be shown to be independent of the discretization size." Could you explain this statement as well? Thank you very much.
