### ISSUE TITLE
The results are inconsistent on windows system and Mac OS system.

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#74]
Dear ubermag team，
When I was simulating a disc skyrmion, I found that the results were different in different systems. 
In Windows I used pip to install ubermag oommf version 1.2.0.3. 
In mac, I installed ubermag as you instructed in YouTube. 
The ubermag in both systems is the latest version updated a few days ago. 
Below, I attach the result diagrams of the two systems and the ipynb file I simulated.
I think it's worth noting that in windows, when I run md.drive, the following shows Tcloommfrunner. 
What is displayed in mac is Exeoommfrunner. 
I don't know if that's why the results are inconsistent.
![3E4C023E56F508810FC913B34B24D567](https://user-images.githubusercontent.com/61874432/86513876-4a2f0000-be40-11ea-9e4c-301b2967c7aa.png)
![image](https://user-images.githubusercontent.com/61874432/86513887-5e72fd00-be40-11ea-9745-e0d277d63761.png)

[interlayer exchange coupled - 副本.zip](https://github.com/ubermag/help/files/4872955/interlayer.exchange.coupled.-.zip)

**Comment by catrevil** [comment]
There’s a few places the discrepancy could be coming from. When you install ubermag via conda, you’re pulling down 2.0a1 version of oommf. This will definitely have a discrepancy when comparing to 1.2.x version of oommf you have installed in Windows OS. 

Actually, I am surprised that the oommf in Windows OS is able to calculate a disc skyrmion!

I might recommend to follow the Windows OS version of the instructions to download ubermag into an isolated conda environment that you’d set up the in the same way you did for Mac OS.

To be clear, what is the version of ubermag that you have on each system?
I ask because conda behaved strangely for me on Windows OS, and did not pull down the most recent update until i told it explicitly to pull the most recent version—I had to provide the current version number to it myself, per Marijan’s instructions.

For Windows OS using ubermag installed as in the YouTube video (i.e., using the packaged 2.0a1) you’ll need to install Docker Desktop so that you can actually run the skyrmion calculations in the most recent ubermag version. Otherwise many tcloommfrunner related errors will occur, which is what is usually used in Windows OS, while Mac OS uses the exeoommfrunner.

In Windows OS, initial initial call for a Docker runner will take about 1 minute for the image to be downloaded, after this it will be callable with timings ~2 seconds or less.

**Comment by code-whale** [comment]
Hi@catrevil, thank you for your answer. Yes, when I first used ubermag in windows, Marijan did not have tutorials on youtube, so I used pip to install all the ubermag-related software packages. At that time, I configured the environment variables myself, and I also tried to use docker, but because of my windows version, it could not be installed on my windows system. I have the latest version of ubermag on both systems. When I look at system.energy in jupyter notebook, they show exactly the same formula, because I know that oommf extensions are inconsistent in windows and mac, so I deliberately use the standard definition values. This is my first time to simulate disc materials, and the results of the two systems are consistent when I simulated rectangular multilayers, so I am not sure what the reason is. Thank you for your suggestion. I'm going to try your suggestion with a virtual machine!

**Comment by catrevil** [comment]
@code-whale can you check the versions and see if they are indeed 0.23 for ubermag and 0.8.22 for oommfc? If so, you should install Docker desktop prior to running the updated code for the Windows OS.

You will find you’ll need to use the 2.0a1 in Windows OS that comes with ubermag inside oommfc if you want your simulations to match.

There’s no need to set up your own VM, this is taken care of automatically through a script updated implemented by Marijan. It will run seamlessly in the background, once you have experienced the initial build time when you first call it. This, of course, as long as you actually have 0.23 ubermag and 0.8.22 for oommfc.

I note again that simple updating procedures did not actually update these for me, and I recommend that you ensure you have actually updated them by checking their versions.

To ensure ubermag is updated, run this in your conda environment dedicated to ubermag: `conda install --channel conda-forge ubermag=0.23`

And install Docker: https://www.docker.com/products/docker-desktop

I hope all of this makes sense!

**Comment by code-whale** [comment]
@catrevil 
I am sorry, I have been busy with some other things recently so that I have time to reply to you now. Due to some problems in my personal computer, I am now installing docker, on my computer. I am temporarily using mac to simulate the operation. I will reload my windows system soon, and then I will follow your suggestion to implement it. If the problem still exists at that time, I will open this problem again. Thank you for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. This difference can be there only due to different OOMMF versions and/or different OOMMF DMI extensions used. It does not have anything to do with ubermag itself. If you still have this problem after you do your reinstallation, please let me know and I can give more information.

**Comment by code-whale** [comment]
@marijanbeg ，After I reinstall, if the problem still exists, I will open the problem again. 
Thank you for your reply!

**Comment by marijanbeg** [comment]
Ok, thanks for letting us know. Could you please share the notebook and give us the differences between two systems (operating system, OOMMF version, conda/docker/tcl path, etc.) Then I can give you more details.

**Comment by code-whale** [comment]
No problem, here are the software versions I use in two systems: 
Windows10:oommf version: 1.2b3; the environment variables are shown in the figure, which I configured myself according to your previous version of the tutorial. 
The updated version of the ubermag package via pip is shown in the following figure and is the latest version you have released. 
MacOS10.15:ubermag follows exactly the installation tutorial you released on YouTube, and the version of oommf I used is also the version that came with ubermag.
I have attached the program I simulated in the form of a compressed package below. You can download it if necessary.
In addition, I found that when I changed the parameters of p1p2, the results of my simulation also changed. In the first file, p1 = (0,0,0) p2 = (300, 300, 6). When I modified it to p1 = (- 150, 150, 0) p2 = (150,150, 6) in the second file, the results of the simulation in mac and windows became consistent. I don't know if there is something wrong with the parameters I set in the first file or something else. If you like, you can take a look at the compressed package I uploaded.


![image](https://user-images.githubusercontent.com/61874432/86769921-7934b400-c082-11ea-83f2-dd0ca6340b84.png)

![image](https://user-images.githubusercontent.com/61874432/86769715-2824c000-c082-11ea-9d2b-d1de4de43604.png)
![image](https://user-images.githubusercontent.com/61874432/86769737-3541af00-c082-11ea-80d8-77425b401e54.png)
![image](https://user-images.githubusercontent.com/61874432/86770201-e8120d00-c082-11ea-82a2-ca9d06bc89d8.png)
![image](https://user-images.githubusercontent.com/61874432/86770225-f19b7500-c082-11ea-9d88-98d389e090d7.png)

[interlayer exchange coupled.zip](https://github.com/ubermag/help/files/4884327/interlayer.exchange.coupled.zip)
[interlayer exchange coupled-changep1p2.zip](https://github.com/ubermag/help/files/4884399/interlayer.exchange.coupled-changep1p2.zip)
