### ISSUE TITLE
Circular subregion and Curie simulation

### ISSUE THREAD

**Issue by daavera** [ubermag/help#83]
Dear Ubermag, thank for the program! I have two questions.

1. Is there a way to define a circular subregion, like, for example, for a two material core-shell?

2. Is there a way to add temperature to the system, such that one can find the Curie temperature? 

Thank!

**Comment by marijanbeg** [comment]
Hi @daavera, thank you for your question and for using Ubermag. Here are the answers to your questions:

1. Since simulations are finite-difference, we only allow defining cubic subregions. However, you can always skip defining subregions and define spatially varying parameters using `Field`. This is the most general solution and allows defining any spatially varying field.

2. Ubermag does not support finite temperature (T>0) simulations.
