### ISSUE TITLE
Hysteresis simulation with time dependent applied field

### ISSUE THREAD

**Issue by daavera** [ubermag/help#86]
Hi everyone. Thanks to the Ubermag team for all their work.

I want to know if anyone has an example of how to implement an hysteresis simulation with an oscillating applied field. I understand that the oc.TimeDriver() has to be used –since the field is varying on time–, but I have not succeeded doing so. 

I'll be grateful for any help.

Thanks.

**Comment by marijanbeg** [comment]
Hi @daavera, thank you for your question. Each point on hysteresis loop represents the relaxed (equilibrium) magnetisation. If you have a time-varying field, you can not reach the equilibrium state due to the external excitation which varies over time.

I am not sure if this answers your question. If not, please feel free to reopen this issue.

**Comment by daavera** [comment]
Hi @marijanbeg , thanks for your answer. Maybe I wasn't clear enough. What I pretend to study is how the area of the hysteresis loop of my system varies with the frequency of the applied field. The micromagnetic field library allows me to add a frequency to the applied field in the Zeeman energy. Nevertheless, when I try to run me simulation with oc.MinDriver() I get an error because the system is time dependent, and when I run it with oc.TimeDriver the simulation never ends. Maybe you know a way in which this 'minimization' can be simulated using applied field with finite frequencies? 

Thanks again for you and your team!
